meeting_channel:
    resource: "@MeetingChannelBundle/Resources/config/routing.yml"
    prefix:   /

meeting_admin:
    resource: "@MeetingAdminBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"