parameters:
#    meeting_channel.example.class: Meeting\ChannelBundle\Example

services:
#    meeting_channel.example:
#        class: %meeting_channel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
