services:

    e.channel:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Meeting\AdminBundle\Entity\Channel ]